#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Employee_Dictionary.Resource", IsApplication=true)]

namespace Employee_Dictionary
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040008
			public const int btnmnAdd = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int btnmnLogin = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int tblmnEmployee = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int txtmnEmail = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int txtmnFirstName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int txtmnJobTitle = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int txtmnLastName = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int txtmnManagerName = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int txtmnManagerPhone = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int txtmnMobileNum = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int txtmnOfficeNum = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int txtmnPassword = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int txtmnUsername = 2130968586;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int EmployeeList = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
